# Generated by Django 3.0 on 2019-12-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_delete_pizzaoncart'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('cart_session', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
