# Generated by Django 3.0 on 2020-01-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191222_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='platter',
            new_name='dinnerplatter',
        ),
    ]
