# Generated by Django 3.0 on 2020-01-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200101_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dinnerplatter',
            field=models.ManyToManyField(blank=True, to='orders.DinnerPlatter'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pasta',
            field=models.ManyToManyField(blank=True, to='orders.Pasta'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pizza',
            field=models.ManyToManyField(blank=True, to='orders.Pizza'),
        ),
        migrations.AlterField(
            model_name='order',
            name='salad',
            field=models.ManyToManyField(blank=True, to='orders.Salad'),
        ),
        migrations.AlterField(
            model_name='order',
            name='sub',
            field=models.ManyToManyField(blank=True, to='orders.Sub'),
        ),
    ]
